### ISSUE TITLE
웨일도 지원해주세요 ㅠ

### ISSUE THREAD

**Issue by zao95** [nix6839/personal-websites#28]
![image](https://github.com/nix6839/personal-websites/assets/35989354/6bf36129-5297-49cb-9218-d16da93fbacf)

웨일도 크로미움 116이면 열심히 따라가는데 지원해주세요 ㅠ

**Comment by nix6839** [comment]
웨일이 117 이상으로 올릴 때까지 기다리는 걸로 ㅜㅜ...
